### PR TITLE
Add support for flipped forward kinematics

### PR DESCRIPTION
**Pull request by tulku**
Sorry did not realize that https://github.com/iron-ox/ridgeback/pull/2 was already merged.

This adds support for the 'flipped' forward kinematics so that the odometry calculation is done correctly. I've added tests to make sure that the 'round trip' between forward and inverse kinematics works.

It's important to note that some values of wheel velocities might transform the forward system into a over determined system, breaking the odometry calculation. I don't think that this will happen with any commanded body velocity, but might happen if an encoder is broken for example.

### CODE REVIEW

**Comment by wongkaiweng** [comment]
@tulku I think the `test/odometry_test.cpp` file is missing. I commented the lines out in `CMakeList.txt` for my testing for now.

**Comment by tulku** [comment]
@wongkaiweng sorry!!! Just added the missing file.

**Review by wongkaiweng — APPROVED** [review]
@tulku. LGTM overall. Do we have a reference to the paper in the code somewhere? I think it will be helpful if we add that in the comment. That way if someone wants to know more about the implementation, he or she knows what this is based on.

**Comment by tulku** [comment]
@wongkaiweng @jonbinney I think that this is mergeable.

**Pull request merged**
